### ISSUE TITLE
Problems compiling `swiftly-forward` branch.

### ISSUE THREAD

**Issue by jordwalke** [vicoapp/vico#88]
I see tons of errors. Do I need to upgrade Xcode version or something?

        /Users/me/github/vico/app/Ruler/ViRulerHelper.swift:29:25: error: expected '{' in extension
        extension ViRulerHelper where Self: NSView {
                                ^
        /Users/me/github/vico/app/Ruler/ViRulerHelper.swift:29:44: error: statement cannot begin with a closure expression
        extension ViRulerHelper where Self: NSView {
                                                   ^
        /Users/me/github/vico/app/Ruler/ViRulerHelper.swift:29:44: note: explicitly discard the result of the closure by assigning to '_'
        extension ViRulerHelper where Self: NSView {
                                                   ^
                                                   _ =
        /Users/me/github/vico/app/Ruler/ViRulerHelper.swift:29:44: error: expressions are not allowed at the top level
        extension ViRulerHelper where Self: NSView {
                                                   ^
        /Users/me/github/vico/app/Ruler/ViRulerHelper.swift:29:44: error: braced block of statements is an unused closure
        extension ViRulerHelper where Self: NSView {
                                                   ^
        /Users/me/github/vico/app/Ruler/ViLineNumberView.swift:205:18: error: consecutive statements on a line must be separated by ';'
                    guard let textStorage = textView.textStorage as? ViTextStorage else {
                         ^
                         ;
        /Users/me/github/vico/app/Ruler/ViLineNumberView.swift:205:75: error: consecutive statements on a line must be separated by ';'
                    guard let textStorage = textView.textStorage as? ViTextStorage else {
                                                                                  ^
                                                                                  ;
        /Users/me/github/vico/app/Ruler/ViLineNumberView.swift:205:76: error: expected expression
                    guard let textStorage = textView.textStorage as? ViTextStorage else {
                                                                                   ^
        /Users/me/github/vico/app/Ruler/ViLineNumberView.swift:205:81: error: braced block of statements is an unused closure
                    guard let textStorage = textView.textStorage as? ViTextStorage else {
                                                                                        ^
        /Users/me/github/vico/app/Ruler/ViLineNumberView.swift:216:14: error: consecutive statements on a line must be separated by ';'
                    } while lineCount > 0
                     ^
                     ;
        /Users/me/github/vico/app/Ruler/ViLineNumberView.swift:216:34: error: expected '{' after 'while' condition
                    } while lineCount > 0
                                         ^
        /Users/me/github/vico/app/Ruler/ViLineNumberView.swift:262:10: error: consecutive statements on a line must be separated by ';'
                } while remainingDigits > 0
                 ^
                 ;
        /Users/me/github/vico/app/Ruler/ViLineNumberView.swift:262:36: error: expected '{' after 'while' condition
                } while remainingDigits > 0
                                           ^
        /Users/me/github/vico/app/Ruler/ViLineNumberView.swift:365:18: error: consecutive statements on a line must be separated by ';'
                        } while UInt(currentCharacterIndex) < lastCharacterIndex
                         ^
                         ;
        /Users/me/github/vico/app/Ruler/ViLineNumberView.swift:365:73: error: expected '{' after 'while' condition
                        } while UInt(currentCharacterIndex) < lastCharacterIndex
                                                                                ^
        /Users/me/github/vico/app/Ruler/ViRulerView.swift:45:18: error: consecutive statements on a line must be separated by ';'
                    guard let textView = self.textView else {
                         ^
                         ;
        /Users/me/github/vico/app/Ruler/ViRulerView.swift:45:47: error: consecutive statements on a line must be separated by ';'
                    guard let textView = self.textView else {
                                                      ^
                                                      ;
        /Users/me/github/vico/app/Ruler/ViRulerView.swift:45:48: error: expected expression
                    guard let textView = self.textView else {
                                                       ^
        /Users/me/github/vico/app/Ruler/ViRulerView.swift:45:53: error: braced block of statements is an unused closure
                    guard let textView = self.textView else {
                                                            ^
        /Users/me/github/vico/app/Ruler/ViRulerView.swift:49:28: error: expected ';' in 'for' statement
                    for var helper in helperConfig.helpers {
                                   ^
        /Users/me/github/vico/app/Ruler/ViRulerView.swift:49:28: error: expected condition in 'for' statement
                    for var helper in helperConfig.helpers {
                                   ^
        /Users/me/github/vico/app/Ruler/ViRulerView.swift:49:28: error: expected ';' in 'for' statement
                    for var helper in helperConfig.helpers {
                                   ^
        /Users/me/github/vico/app/Ruler/ViRulerView.swift:49:28: error: expected expression
                    for var helper in helperConfig.helpers {
                                   ^
        /Users/me/github/vico/app/Ruler/ViRulerView.swift:49:28: error: expected '{' in 'for' statement
                    for var helper in helperConfig.helpers {
                                   ^
        /Users/me/github/vico/app/Ruler/ViRulerView.swift:49:52: error: braced block of statements is an unused closure
                    for var helper in helperConfig.helpers {
                                                           ^
        /Users/me/github/vico/app/Ruler/ViFoldMarginView.swift:121:18: error: consecutive statements on a line must be separated by ';'
                        } while currentCharacterIndex < lastCharacterIndex
                         ^
                         ;
        /Users/me/github/vico/app/Ruler/ViFoldMarginView.swift:121:67: error: expected '{' after 'while' condition
                        } while currentCharacterIndex < lastCharacterIndex
                                                                          ^
        /Users/me/github/vico/app/Text Rendering/ViLayoutManager.swift:49:14: error: failable initializer 'init(coder:)' cannot override a non-failable initializer
            required init?(coder aDecoder: NSCoder) {
                     ^
        AppKit.NSLayoutManager:145:18: note: non-failable initializer 'init(coder:)' overridden here
          @objc required init(coder aDecoder: NSCoder)
                         ^
        /Users/me/github/vico/app/Ruler/ViLineNumberView.swift:84:25: error: overriding method with selector 'observeValueForKeyPath:ofObject:change:context:' has incompatible type '(String?, AnyObject?, [String : AnyObject]?, UnsafeMutablePointer<Void>) -> ()'
            @objc override func observeValueForKeyPath(keyPath: String?, ofObject object: AnyObject?, change: [String : AnyObject]?, context: UnsafeMutablePointer<Void>) {
                                ^
        Foundation.NSObject:3:14: note: overridden declaration here has type '(String, AnyObject, [NSObject : AnyObject], UnsafeMutablePointer<Void>) -> Void'
          @objc func observeValueForKeyPath(keyPath: String, ofObject object: AnyObject, change: [NSObject : AnyObject], context: UnsafeMutablePointer<Void>)
                     ^

        2015-10-02 15:50:22.435 xcodebuild[12829:2790136]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7703/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
        Details:  Failed to load dependencies output contents from ``/Users/me/Library/Developer/Xcode/DerivedData/vico-dapsfhmcfbrnypcyfttxrtkhfwdj/Build/Intermediates/vico.build/Debug/Vico.build/Objects-normal/x86_64/Dictionary-typedAccess.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “Dictionary-typedAccess.d” couldn’t be opened because there is no such file." UserInfo=0x7ff44387ca20 {NSFilePath=/Users/me/Library/Developer/Xcode/DerivedData/vico-dapsfhmcfbrnypcyfttxrtkhfwdj/Build/Intermediates/vico.build/Debug/Vico.build/Objects-normal/x86_64/Dictionary-typedAccess.d, NSUnderlyingError=0x7ff4438c7c40 "The operation couldn’t be completed. No such file or directory"}. User info: {
            NSFilePath = "/Users/me/Library/Developer/Xcode/DerivedData/vico-dapsfhmcfbrnypcyfttxrtkhfwdj/Build/Intermediates/vico.build/Debug/Vico.build/Objects-normal/x86_64/Dictionary-typedAccess.d";
            NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
        }.

**Comment by Shadowfiend** [comment]
Hey there, do keep discussions about that branch to the PR that references it—it's still experimental so no need to clutter the issue list with it :)

That said, currently that branch requires XCode 7 and Swift 2. I'm working on it on El Cap. It's still somewhat unstable though, and I'm working through various odd crashes here and there in some situations.

**Comment by Shadowfiend** [comment]
(The PR for it is #86.)

**Comment by jordwalke** [comment]
Do you prefer comments/questions on the specific pull requests?

**Comment by Shadowfiend** [comment]
Yes indeed!
